
db.createCollection( 'usuario', {validator: {$jsonSchema: {bsonType: 'object',title:'usuario',required: [         '_idUsuario',          'nombre',          'password',          'email',          'fechaNacim',          'sexo',          'cp',          'tipoUsuario',          'playlist',          'cancionesFavoritas',          'albunesFavoritos'],properties: {_idUsuario: {bsonType: 'objectId'},nombre: {bsonType: 'string'},password: {bsonType: 'string'},email: {bsonType: 'string'},fechaNacim: {bsonType: 'date'},sexo: {enum: (femenino, masculino)},cp: {bsonType: 'int'},pais: {bsonType: 'string'},tipoUsuario: {bsonType: 'array',items: {
title:'object',required: [         'usuarioFree',          'usuarioPremium',          'idTipoUsuario'],properties: {usuarioFree: {bsonType: 'string'},usuarioPremium: {bsonType: 'array',items: {
title:'object',required: [         'idUsuario',          'suscripcion'],properties: {idUsuario: {bsonType: 'int'},suscripcion: {bsonType: 'array',items: {
title:'object',required: [         'diaInicio',          'diaRenovacion',          'formaPago',          'idSubscripcion'],properties: {diaInicio: {bsonType: 'date'},diaRenovacion: {bsonType: 'date'},formaPago: {bsonType: 'array',items: {
title:'object',required: [         'Paypal',          'TC',          'idFormaPago'],properties: {Paypal: {bsonType: 'array',items: {
title:'object',required: [         'idPaypal',          'nombreUsuario'],properties: {idPaypal: {bsonType: 'int'},nombreUsuario: {bsonType: 'string'}}}},TC: {bsonType: 'array',items: {
title:'object',required: [         'idTC',          'numTC',          'fechaCaducidad',          'CVV'],properties: {idTC: {bsonType: 'int'},numTC: {bsonType: 'int'},fechaCaducidad: {bsonType: 'date'},CVV: {bsonType: 'int'}}}},idFormaPago: {bsonType: 'int'}}}},idSubscripcion: {bsonType: 'int'}}}}}}},idTipoUsuario: {bsonType: 'int'}}}},playlist: {bsonType: 'array',items: {
title:'object',required: [         'idPlaylist',          'titulo',          'nombreCancion',          'fechaCreacion',          'tipoPlaylist'],properties: {idPlaylist: {bsonType: 'int'},titulo: {bsonType: 'string'},nombreCancion: {bsonType: 'string'},fechaCreacion: {bsonType: 'date'},tipoPlaylist: {bsonType: 'array',items: {
title:'object',required: [         'idTipoPlaylis',          'activos',          'borradas'],properties: {idTipoPlaylis: {bsonType: 'int'},activos: {bsonType: 'array',items: {
title:'object',required: [         'idActiva',          'playlistCompartidas'],properties: {idActiva: {bsonType: 'int'},playlistCompartidas: {bsonType: 'array',items: {
title:'object',required: [         'nombre',          'fecha',          'idPlaylistCompartida'],properties: {nombre: {bsonType: 'string'},fecha: {bsonType: 'date'},idPlaylistCompartida: {bsonType: 'string'}}}}}}},borradas: {bsonType: 'array',items: {
title:'object',required: [         'id_borrada',          'fechaBorradas'],properties: {id_borrada: {bsonType: 'int'},fechaBorradas: {bsonType: 'date'}}}}}}}}}},cancionesFavoritas: {bsonType: 'array',items: {
title:'object',required: [         'idCancionesFavoritas'],properties: {nombreCanciones: {bsonType: 'array',items: {bsonType: 'string'}},idCancionesFavoritas: {bsonType: 'array',items: {bsonType: 'string'}}}}},albunesFavoritos: {bsonType: 'array',items: {
title:'object',required: [         'idAlbunesFavoritos',          'albunes Favoritos'],properties: {idAlbunesFavoritos: {bsonType: 'int'},albunes Favoritos: {bsonType: 'array',items: {}}}}}}         }      }});  