
db.createCollection( 'tienda', {validator: {$jsonSchema: {bsonType: 'object',title:'tienda',required: [         'nombre',          'direccion',          'cp',          'direccion',          'trabajadores',          'productos ',          'pedido'],properties: {nombre: {bsonType: 'string'},direccion: {bsonType: 'string'},cp: {bsonType: 'int'},direccion: {bsonType: 'object',
title:'object',required: [         'nombreProvincia',          'id_provincia',          'localidades'],properties: {nombreProvincia: {bsonType: 'string'},id_provincia: {bsonType: 'int'},localidades: {bsonType: 'array',items: {
title:'object',required: [         'id_localidad',          'nombreLocalidad'],properties: {id_localidad: {bsonType: 'int'},nombreLocalidad: {bsonType: 'string'}}}}}},trabajadores: {bsonType: 'array',items: {
title:'object',required: [         'id_trabajador',          'nombre',          'apellido',          'nif',          'telf',          'cargo'],properties: {id_trabajador: {bsonType: 'string'},nombre: {bsonType: 'string'},apellido: {bsonType: 'string'},nif: {bsonType: 'int'},telf: {bsonType: 'int'},cargo: {bsonType: 'object',
title:'object',required: [         'cocinero',          'repartidorDomicilio'],properties: {cocinero: {bsonType: 'bool'},repartidorDomicilio: {bsonType: 'object',
title:'object',required: [         'nombre',          'diaHora'],properties: {nombre: {bsonType: 'string'},diaHora: {bsonType: 'timestamp'}}}}}}}},productos : {bsonType: 'array',items: {
title:'object',required: [         'nombre',          'descripcion',          'imgen',          'precio',          'tipoProducto',          'categoriasProducto',          'id_productos'],properties: {nombre: {bsonType: 'string'},descripcion: {bsonType: 'string'},imgen: {bsonType: 'string'},precio: {bsonType: 'decimal'},tipoProducto: {enum: (pizzas,hamburguesas,bebidas)},categoriasProducto: {bsonType: 'array',items: {
title:'object',required: [         'Pizzas',          'hamburguesas',          'bebidas',          'VariedadPizzas',          '_idCategoriasProducto'],properties: {Pizzas: {bsonType: 'bool'},hamburguesas: {bsonType: 'bool'},bebidas: {bsonType: 'bool'},VariedadPizzas: {bsonType: 'array',items: {
title:'object',required: [         'nombre',          '_idVariedadPizzas'],properties: {nombre: {bsonType: 'string'},_idVariedadPizzas: {bsonType: 'string'}}}},_idCategoriasProducto: {bsonType: 'string'}}}},id_productos: {bsonType: 'array',items: {bsonType: 'string'}}}}},pedido: {bsonType: 'array',items: {
title:'object',required: [         'id_pedido',          'cliente',          'venta'],properties: {id_pedido: {bsonType: 'int'},cliente: {bsonType: 'array',items: {
title:'object',required: [         'id_cliente',          'nombre',          'apellido',          'cp',          'telefono',          'direccion'],properties: {id_cliente: {bsonType: 'string'},nombre: {bsonType: 'string'},apellido: {bsonType: 'string'},cp: {bsonType: 'int'},telefono: {bsonType: 'int'},direccion: {bsonType: 'object',
title:'object',required: [         'id_Provincia',          'nombre',          'localidad'],properties: {id_Provincia: {bsonType: 'string'},nombre: {bsonType: 'string'},localidad: {bsonType: 'array',items: {
title:'object',required: [         'id_localidad',          'nombre'],properties: {id_localidad: {bsonType: 'string'},nombre: {bsonType: 'string'}}}}}}}}},venta: {bsonType: 'array',items: {
title:'object',required: [         'tipoVenta',          'repartoDomicilio',          '_idTipoVenta'],properties: {tipoVenta: {enum: (Tienda, repartoDomicilio)},repartoDomicilio: {bsonType: 'array',items: {
title:'object',required: [         'nombreRepartidor',          'diaHora',          'id_repartoDomicilio'],properties: {nombreRepartidor: {bsonType: 'array',items: {bsonType: 'string'}},diaHora: {bsonType: 'timestamp'},id_repartoDomicilio: {bsonType: 'string'}}}},_idTipoVenta: {bsonType: 'string'}}}}}}}}         }      }});  
 db.tienda.createIndex(
)

